#!/bin/bash

echo "=== Cloudflare Tunnel 设置指南 ==="
echo ""
echo "1. 安装 cloudflared:"
echo "   brew install cloudflare/cloudflare/cloudflared"
echo ""
echo "2. 登录 Cloudflare:"
echo "   cloudflared tunnel login"
echo ""
echo "3. 创建隧道:"
echo "   cloudflared tunnel create xu-geng-doctor"
echo ""
echo "4. 运行隧道:"
echo "   cloudflared tunnel --url http://localhost:3000"
echo ""
echo "这会给你一个真实的 HTTPS URL，可以在手机上安装PWA！"
echo ""
echo "或者使用快速命令（无需登录）:"
echo "   cloudflared tunnel --url http://localhost:3000"
